### PR TITLE
Feat: Message drafts (save partial messages in local storage)

### PR DESCRIPTION
**Pull request by acidbubbles**
This solves #141 and saves drafts in the local storage to restore them later if you come back to the chat.

The draft is cleared if you send the message or if you delete the chat.

This PR is ready to be merged.

Notes:

- I replaced the debounce implementation, since the previous one wasn't used and didn't really debounce
- I noticed local storage was also used to "restore" previous chats, but as far as I can tell the only way to use this "last chat" feature is to go to /chat, which isn't accessible unless you know the URL. I suggest deleting that code.
- It's also weird that it's not /chats/{id} and it's instead /chat/{id}. Ok to change it?

### CODE REVIEW

**Comment by acidbubbles** [comment]
Oh and by the way that also solves a minor bug; the InputBar received the chats.chat object, which had the _previous_ value when the component was created. Meaning this line:

```js
<Show when={!!state.lastMsg?.characterId && props.chat.userId === user.user?._id}>
```

was not using the correct props.chat.

**Comment by sceuick** [comment]
I want to merge this PR, but I just noticed the class that manages the draft state. That state should be moved to a store as that's what they're for.

**Comment by acidbubbles** [comment]
@sceuick Added a store (I think I finally groked the SolidJS stores, I knew rxjs and I prefer Solid's stores now!)

When trying to figure out why I was missing a character in multi mode's events, I realized the single and multi, after refactoring a little, really had a single difference: in one case, shift enter added a line, in the other, it did not.

So I also fixed https://github.com/luminai-companion/agn-ai/issues/126#issuecomment-1517238598 in this PR, I'd split them in two but it was much easier to see why it could be deleted in the diff if they were together, and they would have conflicted otherwise. Hope it's okay!

**Comment by acidbubbles** [comment]
I removed the chat() effect, the goal was to avoid having the incorrect active chat for a given route, but I used another approach instead (filtering the state value), hopefully it'll be easier to rebase (or event better, get merged ;) )

**Pull request merged**
