### PR TITLE
feat: OOC messages for multi-user rooms

### PR DESCRIPTION
**Pull request by malfoyslastname**
addresses part of #182

This PR adds a toggle left of the message input that can be in "OOC" or "RP" mode. "RP" mode is the "normal" mode which sends a message seen by the bot, and included prompts. "OOC" mode is a new mode which sends a message ignored by the bot, and not included in prompts.

This toggle is only shown when at least two users are in a room. It can be forced to be shown on a single-user room by using the dev command `/devShowOocToggle`

The default mode is "RP" in single-user rooms, and "OOC" in multi-user rooms.

A chat setting toggle is also added in multi-user rooms to hide OOC messages, making it easier to take screenshots. (Not demonstrated in below video)

(also: ui: remove right-margin on message icons (e.g. trash), it looks bad with msg background on)

### Demo

https://user-images.githubusercontent.com/128472336/234120884-c0dd303e-dce8-44b9-8246-e8be3f91c810.mp4

### CODE REVIEW

**Comment by malfoyslastname** [comment]
[d4047e0](https://github.com/luminai-companion/agn-ai/pull/249/commits/d4047e0519574fcdf4f85a9740cd588aca6211d7) [d4047e0](https://github.com/luminai-companion/agn-ai/pull/249/commits/d4047e0519574fcdf4f85a9740cd588aca6211d7)

**Comment by acidbubbles** [comment]
That looks great, I'm wondering about OOC though, because if might not be intuitive for everyone, and I'm sending OOC messages myself with bots to explain how I want them to behave :)

Maybe instead a "visible to bots" toggle (switch between robot icon and no robot icon)?

Otherwise, visually it really looks like the idea I had for events. Instead of just robots / no robots, slash commands would be great although less discoverable.

Here's an idea: a slash button, which opens like a drop down, and gives a list of existing commands, such as "send only to users". Then that could be a mode until you toggle it off I guess. This helps because it allows for more text, and it can be invoked without the mouse.

Those were my thoughts but I have no authority here! :P

**Comment by malfoyslastname** [comment]
> That looks great, I'm wondering about OOC though, because if might not be intuitive for everyone, and I'm sending OOC messages myself with bots to explain how I want them to behave :)
> Maybe instead a "visible to bots" toggle (switch between robot icon and no robot icon)?

My main requirement for best UX is having a single-click toggle (in multi-user rooms), unfortunately the "indicator" must be narrow in order to play well with mobile so I had to come up with RP vs OOC as shortnames. Robot icon and no robot icon seems like a decent alternative but still not great. (Whatever @sceuick prefers I'm game.)

I'm open to thinking about slash commands (would it still be one click?) but this would take a lot of UX consideration I think. Can we ship this the way it is and be open to future changes?

**Comment by sceuick** [comment]
I'd like to get this merged very soon. If we can rebase it then fiddle with the UI/UX in a subsequent PR (because it's currently behind a flag?) then we'll be sweet. It can probably be a toggle in the InputBar DropUp menu?

**Comment by malfoyslastname** [comment]
@sceuick it's not behind a flag, it's enabled for multi-user rooms. The dev command I used is to force it to appear on single-user rooms.

**Comment by malfoyslastname** [comment]
@sceuick latest dev changes merged. feature re-tested ok.

**Comment by sceuick** [comment]
After merging TTS and STT this PR needs rebasing again :(
Can you rebase it one last time?

**Comment by malfoyslastname** [comment]
@sceuick done and re-tested. didn't re-test STT/TTS

**Pull request merged**
