### PR TITLE
openai support

### PR DESCRIPTION
**Pull request by ewof**
user defines an OpenAI key in settings
image
user defines frequency penalty, presence penalty, which model to use, and gaslight prompt (if turbo)
image

just werks
i dont write ts a lot pls review make sure i didn't write anything fucked

### CODE REVIEW

**Comment by sceuick** [comment]
Thanks for the PR! I've just pulled the branch. I'll take a look.

**Comment by sceuick** [comment]
Excellent work! I'll make a few small tweaks and comments:
- I assume you intended to `.replace(/{{scenario}}/g, char.scenario)` in the adapter
- I like the idea of the model being set in the GenSettings instead of the Config. I should have done that for Novel!
- I also used `formatCharacter()` when inserting the character's persona. This will output W++,Boo,SBF,etc. I assume this is what you intended? I think the previous code would have output `[object Object]` in the message instead of the persona.

**Comment by sceuick** [comment]
See the commit I just pushed. [7287675](https://github.com/luminai-companion/agn-ai/pull/16/commits/7287675ac78b9ccc966c6012a6da27d019aef5b5)

May be worth giving it a test. If you're happy with it, we can merge it :+1:

**Comment by ewof** [comment]
tiny nitpick is that in the modal for gen settings in the conversation page, when u use a preset it doesn't update the values and bc the textinput and dropdown components have no indication when theyre disabled (like how number inputs are greyed out for example) it looks like it isnt actually using the correct model in the preset even tho it is
other than that lgtm

**Comment by sceuick** [comment]
> tiny nitpick is that in the modal for gen settings in the conversation page, when u use a preset it doesn't update the values and bc the textinput and dropdown components have no indication when theyre disabled (like how number inputs are greyed out for example) it looks like it isnt actually using the correct model in the preset even tho it is other than that lgtm

I _think_ I can solve this pretty easily. I'll try to fix it at the same time as the iOS Safari modal fix.

**Comment by sceuick** [comment]
Sorry about those typos, I'm on my laptop :joy:

**Pull request merged**
