### PR TITLE
Feat: Favorite characters

### PR DESCRIPTION
**Pull request by acidbubbles**
image

- New api /char/:id/favorite
- When there's one favorite, split the list, but otherwise don't split it
- Works with both local and logged in storage

### CODE REVIEW

**Comment by sceuick** [comment]
Heya, I'm probably going to need your help rebasing this one now that the character list has changed so much.
I'd definitely love to get this one merged. It's a very nice QoL feature to have!

**Comment by acidbubbles** [comment]
Just so you know I wanted to add grouping options instead of just hardcoding favorites, but then went on a rabbit hole of cleaning up the filters ui. I'll submit the changes soon, I can always split them in separate PRs if you want but I think you'll like it.

I had to learn tailwind to do that, so there's some blood in this PR.

I'll send a screenshot when ready.

**Comment by acidbubbles** [comment]
As advertised.

image

Note that I pan the cards higher so there are more chances to see the relevant part of the face on landscape placeholders.

Also works on mobile

image

Normalized the chats view

image

Also added sort by chat created. When choosing a specific character, it will sort by activity desc automatically and only offer chat-specific sorts.

Phew! Oh, and favorites work :D

**Comment by acidbubbles** [comment]
All changes discussed on Discord done

image

- Max card width
- Better UI break on mobile
- Secondary button style

**Pull request merged**
